# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asp_frsname', models.CharField(max_length=15, verbose_name='Primer Nombre')),
                ('asp_midname', models.CharField(max_length=15, verbose_name='Segundo Nombre')),
                ('asp_secmanp', models.CharField(max_length=25, verbose_name='Apellidos')),
                ('asp_secmanm', models.CharField(max_length=25, verbose_name='Apellidos')),
                ('asp_fechnac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('asp_direcci', models.CharField(max_length=50, verbose_name='Direccion Domiciliaria')),
                ('asp_telefon', models.CharField(blank=True, max_length=15, verbose_name='Telefono')),
                ('asp_celular', models.CharField(blank=True, max_length=15, verbose_name='Celular')),
                ('asp_correoe', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('asp_imgclte', models.ImageField(blank=True, upload_to='clientes')),
                ('asp_rgunico', models.CharField(blank=True, max_length=20, verbose_name='Registro Unico')),
                ('asp_categor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evn_fechaev', models.DateField(verbose_name='Fecha deEvento')),
                ('evn_direcci', models.TextField(max_length=75, verbose_name='Dirección')),
                ('evn_localid', models.TextField(max_length=50, verbose_name='Local')),
                ('evn_asisten', models.IntegerField(verbose_name='Cantida de asistentes')),
                ('evn_pendien', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eml_fechmsj', models.DateField(verbose_name='Fecha de Mensaje')),
                ('eml_descrip', models.EmailField(max_length=254, verbose_name='email')),
                ('eml_mensaje', models.TextField(verbose_name='Mensaje')),
                ('eml_requier', models.BooleanField(default=False)),
                ('eml_aspiran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Zipcodigo',
            fields=[
                ('zip_idzipco', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código Postal')),
                ('zip_country', models.TextField(max_length=5, verbose_name='Pais')),
                ('zip_estddet', models.TextField(max_length=30, verbose_name='Estado')),
                ('zip_estdabr', models.TextField(max_length=5, verbose_name='Estado')),
                ('zip_condado', models.TextField(max_length=35, verbose_name='Condado')),
                ('zip_ciuddet', models.TextField(max_length=35, verbose_name='Ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='evn_zipcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Zipcodigo'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='asp_zipcodg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Zipcodigo'),
        ),
    ]
