# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20180311_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirante',
            name='asp_zipcodg',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='eml_aspiran',
        ),
        migrations.DeleteModel(
            name='Aspirante',
        ),
    ]
