from django import forms
from .models import Cajera, Caja, Movicaja, Plancuenta, Saldocontab, Comprobante

from django.utils.timezone import localtime, now


class CajeraForm(forms.ModelForm):
    class Meta:
        model = Cajera

        fields = [
                'cjr_frsname',
                'cjr_midname',
                'cjr_lasname',
                'cjr_fechnac',
                'cjr_direcci',
                'cjr_ciudade',
                'cjr_estados',
                'cjr_country',
                'cjr_zipcodg',
                'cjr_telefon',
                'cjr_celular',
                'cjr_correoe',
                'cjr_imgcjer',
                'cjr_rgunico',
                'cjr_categor',
                ]
        labels = {
                'cjr_frsname':  'Primer Nombre',
                'cjr_midname':  'Segundo Nombre',
                'cjr_lasname':  'Apellidos',
                'cjr_fechnac':  'Fecha de Nacimiento',
                'cjr_direcci':  'Dirección',
                'cjr_ciudade':  'Ciudad',
                'cjr_estados':  'Provincia',
                'cjr_country':  'Pais',
                'cjr_zipcodg':  'Cód. Postal',
                'cjr_telefon':  'Núm. de telefono',
                'cjr_celular':  'Núm. de Celular',
                'cjr_correoe':  'E-mail',
                'cjr_imgcjer':  'Foto de Clte.',
                'cjr_rgunico':  'Reg. único',
                'cjr_categor':  'Categoría',
                }
        widgets = {
                'cjr_frsname': forms.TextInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cjr_midname': forms.TextInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cjr_lasname': forms.TextInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cjr_fechnac': forms.DateInput(attrs={"type": "date"}),
                'cjr_direcci': forms.TextInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cjr_ciudade': forms.Select(),
                'cjr_estados': forms.Select(),
                'cjr_country': forms.Select(),
                'cjr_zipcodg': forms.Select(),
                'cjr_telefon': forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cjr_celular': forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cjr_correoe': forms.EmailInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cjr_imgcjer': forms.ClearableFileInput(),
                'cjr_rgunico': forms.TextInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cjr_categor': forms.Select(),
                }


class CajaForm(forms.ModelForm):
    class Meta:
        model = Caja
        fields = [
                'cja_numcaja',
                'cja_plancta',
                'cja_monedas',
                'cja_cotizac',
                'cja_fchultm',
                'cja_cajeras',
                'cja_inicash',
                'cja_ingcash',
                'cja_egrcash',
                'cja_salcash',
                'cja_inicchq',
                'cja_ingrchq',
                'cja_egrechq',
                'cja_saldchq',
                'cja_inictjc',
                'cja_ingrtjc',
                'cja_egretjc',
                'cja_saldtjc',
                'cja_inicred',
                'cja_ingcred',
                'cja_egrcred',
                'cja_salcred',
                'cja_inicotr',
                'cja_ingrotr',
                'cja_egreotr',
                'cja_saldotr',
                'cja_fcharqe',
                'cja_numarqe',
                'cja_arqefec',
                'cja_arqcheq',
                'cja_arqtjcr',
                'cja_arqcred',
                'cja_arqotro',
        ]
        labels = {
                'cja_numcaja':  'Núm. de caja',
                'cja_plancta':  'Cta. contable',
                'cja_monedas':  'Moneda',
                'cja_cotizac':  'Cotización',
                'cja_fchultm':  'Fecha de ult. mov.',
                'cja_cajeras':  'Cajera por default',
                'cja_inicash':  'Saldo inicial cash',
                'cja_ingcash':  'Saldo ingreso cash',
                'cja_egrcash':  'Saldo egreso  cash',
                'cja_salcash':  'Saldo actual  cash',
                'cja_inicchq':  'Saldo inicial Cheq.',
                'cja_ingrchq':  'Saldo ingreso Cheq.',
                'cja_egrechq':  'Saldo egreso  Cheq.',
                'cja_saldchq':  'Saldo actual  Cheq.',
                'cja_inictjc':  'Saldo inicial T/Cr.',
                'cja_ingrtjc':  'Saldo ingreso T/Cr.',
                'cja_egretjc':  'Saldo egreso  T/Cr.',
                'cja_saldtjc':  'Saldo actual  T/Cr.',
                'cja_inicred':  'Saldo inicial Cred.',
                'cja_ingcred':  'Saldo ingreso Cred.',
                'cja_egrcred':  'Saldo egreso  Cred.',
                'cja_salcred':  'Saldo actual  Cred.',
                'cja_inicotr':  'Saldo inicial Otro',
                'cja_ingrotr':  'Saldo ingreso Otro',
                'cja_egreotr':  'Saldo egreso  Otro',
                'cja_saldotr':  'Saldo actual  Otro',
                'cja_fcharqe':  'Fecha de arqueo',
                'cja_numarqe':  'Num. de arqueo',
                'cja_arqefec':  'Arqueo inicial Cash',
                'cja_arqcheq':  'Arqueo ingreso Cheq.',
                'cja_arqtjcr':  'Arqueo egreso  T/Cr.',
                'cja_arqcred':  'Arqueo actual  Cred.',
                'cja_arqotro':  'Arqueo actual  Otro',
                  }
        widgets = {
                # 'cja_numcaja': forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cja_plancta': forms.Select(),
                'cja_monedas': forms.Select(),
                'cja_cotizac': forms.DecimalField(decimal_places=2),
                'cja_fchultm': forms.DateInput(attrs={"type": "date"}),
                'cja_cajeras': forms.Select(),
                'cja_inicash': forms.DecimalField(decimal_places=2),
                'cja_ingcash': forms.DecimalField(decimal_places=2),
                'cja_egrcash': forms.DecimalField(decimal_places=2),
                'cja_salcash': forms.DecimalField(decimal_places=2),
                'cja_inicchq': forms.DecimalField(decimal_places=2),
                'cja_ingrchq': forms.DecimalField(decimal_places=2),
                'cja_egrechq': forms.DecimalField(decimal_places=2),
                'cja_saldchq': forms.DecimalField(decimal_places=2),
                'cja_inictjc': forms.DecimalField(decimal_places=2),
                'cja_ingrtjc': forms.DecimalField(decimal_places=2),
                'cja_egretjc': forms.DecimalField(decimal_places=2),
                'cja_saldtjc': forms.DecimalField(decimal_places=2),
                'cja_inicred': forms.DecimalField(decimal_places=2),
                'cja_ingcred': forms.DecimalField(decimal_places=2),
                'cja_egrcred': forms.DecimalField(decimal_places=2),
                'cja_salcred': forms.DecimalField(decimal_places=2),
                'cja_inicotr': forms.DecimalField(decimal_places=2),
                'cja_ingrotr': forms.DecimalField(decimal_places=2),
                'cja_egreotr': forms.DecimalField(decimal_places=2),
                'cja_saldotr': forms.DecimalField(decimal_places=2),
                'cja_fcharqe': forms.DateInput(attrs={"type": "date"}),
                'cja_numarqe': forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cja_arqefec': forms.DecimalField(decimal_places=2),
                'cja_arqcheq': forms.DecimalField(decimal_places=2),
                'cja_arqtjcr': forms.DecimalField(decimal_places=2),
                'cja_arqcred': forms.DecimalField(decimal_places=2),
                'cja_arqotro': forms.DecimalField(decimal_places=2),
        }


class MovicajaForm(forms.ModelForm):
    mcj_fechmov = forms.DateField(initial=localtime(now()).date())

    class Meta:
        model = Movicaja
        fields = [
                'mcj_compcja',
                'mcj_sucursa',
                'mcj_monedas',
                'mcj_cotizac',
                'mcj_fechmov',
                'mcj_cajanum',
                'mcj_cajeras',
                'mcj_tipomov',
                'mcj_numdocu',
                'mcj_valcash',
                'mcj_valcheq',
                'mcj_valtjcr',
                'mcj_valcred',
                'mcj_valotro',
                'mcj_imgcomp',
        ]
        labels = {

                'mcj_compcja':  'Comprobante de caja',
                'mcj_sucursa':  'Sucursal',
                'mcj_monedas':  'Moneda',
                'mcj_cotizac':  'Cotización',
                'mcj_fechmov':  'Fecha mov. en caja',
                'mcj_cajanum':  'Caja',
                'mcj_cajeras':  'Cajera',
                'mcj_tipomov':  'Tipo de movim.',
                'mcj_numdocu':  'Núm. de documento',
                'mcj_valcash':  'Valor en efectivo',
                'mcj_valcheq':  'Valor en Cheque',
                'mcj_valtjcr':  'Valor en T.Crúdito',
                'mcj_valcred':  'Valor Cred.personal',
                'mcj_valotro':  'Valor en otros',
                'mcj_imgcomp':  'Imagen Comp/Caja',
                }
        widgets = {
                'mcj_compcja': forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'mcj_sucursa': forms.Select(),
                'mcj_monedas': forms.Select(),
                'mcj_cotizac': forms.DecimalField(decimal_places=2),
                'mcj_fechmov': forms.DateInput(attrs={"type": "date"}),
                'mcj_cajanum': forms.Select(),
                'mcj_cajeras': forms.Select(),
                'mcj_codtran': forms.Select(),
                'mcj_tipomov': forms.Select(),
                'mcj_numdocu': forms.DecimalField(decimal_places=2),
                'mcj_valcash': forms.DecimalField(decimal_places=2),
                'mcj_valcheq': forms.DecimalField(decimal_places=2),
                'mcj_valtjcr': forms.DecimalField(decimal_places=2),
                'mcj_valcred': forms.DecimalField(decimal_places=2),
                'mcj_valotro': forms.DecimalField(decimal_places=2),
                'mcj_imgcomp': forms.ClearableFileInput(),
                }


class Plancuentaform(forms.ModelForm):

    class Meta:
        model = Plancuenta
        fields = [
                'plc_ncuenta',
                'plc_cuenta1',
                'plc_cuenta2',
                'plc_cuenta3',
                'plc_cuenta4',
                'plc_auxili1',
                'plc_auxili2',
                'plc_auxili3',
                'plc_detalle',
                'plc_ctabaln',
                'plc_ctanexo',
                'plc_ctarsul',
                'plc_ctamyor',
                'plc_nivlcta',
                'plc_tipocta',
                ]

        labels = {
                'plc_ncuenta': 'Núm. de cuenta',
                'plc_cuenta1': 'Cta.Nivel-1',
                'plc_cuenta2': 'Cta.Nivel-2',
                'plc_cuenta3': 'Cta.Nivel-3',
                'plc_cuenta4': 'Cta.Nivel-4',
                'plc_auxili1': 'Cta.Auxiliar-1',
                'plc_auxili2': 'Cta.Auxiliar-2',
                'plc_auxili3': 'Cta.Auxiliar-3',
                'plc_detalle': 'Nombre de la cta.',
                'plc_ctabaln': 'Cuenta  de baalance',
                'plc_ctanexo': 'Cta. para los anexos',
                'plc_ctarsul': 'Cta. para resultados (p/g)',
                'plc_ctamyor': 'Cta. para mayotizarce',
                'plc_nivlcta': 'Nivel Cta. 1 a 7',
                'plc_tipocta': 'Naturaleza de cta D/C',
                }
        widgets = {
                'plc_ncuenta': forms.TextInput(attrs={"autocomplete": "off"}),
                'plc_cuenta1': forms.TextInput(attrs={"autocomplete": "off", 'size': '1'}),
                'plc_cuenta2': forms.TextInput(attrs={"autocomplete": "off", 'size': '1'}),
                'plc_cuenta3': forms.TextInput(attrs={"autocomplete": "off", 'size': '1'}),
                'plc_cuenta4': forms.TextInput(attrs={"autocomplete": "off", 'size': '1'}),
                'plc_auxili1': forms.TextInput(attrs={"autocomplete": "off", 'size': '2'}),
                'plc_auxili2': forms.TextInput(attrs={"autocomplete": "off", 'size': '2'}),
                'plc_auxili3': forms.TextInput(attrs={"autocomplete": "off", 'size': '2'}),
                'plc_detalle': forms.TextInput(attrs={"autocomplete": "off", 'size': '40'}),
                'plc_ctabaln': forms.TextInput(attrs={"autocomplete": "off", 'size': '1'}),
                'plc_ctanexo': forms.TextInput(attrs={"autocomplete": "off", 'size': '1'}),
                'plc_ctarsul': forms.TextInput(attrs={"autocomplete": "off", 'size': '1'}),
                'plc_ctamyor': forms.TextInput(attrs={"autocomplete": "off", 'size': '1'}),
                'plc_nivlcta': forms.TextInput(attrs={"autocomplete": "off", 'size': '1'}),
                'plc_tipocta': forms.TextInput(attrs={"autocomplete": "off", 'size': '1'}),
                }


class ComprobanteForm(forms.ModelForm):
    cmp_fechcmp = forms.DateField(initial=localtime(now()).date())

    class Meta:
        model = Comprobante
        fields = [
                'cmp_comprob',
                'cmp_ncuenta',
                'cmp_fechcmp',
                'cmp_usernam',
                'cmp_sucursa',
                'cmp_origpro',
                'cmp_origtra',
                'cmp_numorig',
                'cmp_tpoenti',
                'cmp_entidad',
                'cmp_mondalt',
                'cmp_mondaof',
                'cmp_cotizac',
                'cmp_cajanum',
                'cmp_cajeras',
                'cmp_detalle',
                'cmp_cantida',
                'cmp_tpomovi',
                'cmp_valores',
                'cmp_nivlcta',
                'cmp_periodo',
                'cmp_costord',
                'cmp_costcta',
                'cmp_imgcomp',
                'cmp_statreg',
        ]
        labels = {
                'cmp_comprob':  'Núm. Comprobante',
                'cmp_ncuenta':  'Cuenta/Plan de Ctas.',
                'cmp_fechcmp':  'Fecha de comprobante',
                'cmp_usernam':  'User',
                'cmp_sucursa':  'Sucursal',
                'cmp_origpro':  'Origen del proceso=programa de origen',
                'cmp_origtra':  'Origen de transacción (F=Factura,C=Compra,Cheques, hacer Tabla)',
                'cmp_numorig':  'Numero o ref. de origen',
                'cmp_tpoenti':  'Tipo de entidad (C=Cliente,P=Proveedor,hacer Tabla)',
                'cmp_entidad':  'Código de entidad',
                'cmp_mondalt':  'Moneda alterna',
                'cmp_mondaof':  'Moneda oficial',
                'cmp_cotizac':  'Cotización',
                'cmp_cajanum':  'Núm. de caja',
                'cmp_cajeras':  'Cód. de Cajera',
                'cmp_detalle':  'Detalle del movimiento',
                'cmp_cantida':  'Cantidad',
                'cmp_tpomovi':  'Tipo de Movimiento D=Débito, C=Credito, I=Inicial',
                'cmp_valores':  'Valor',
                'cmp_nivlcta':  'Nivel de cta.',
                'cmp_periodo':  'Periodo contable',
                'cmp_costord':  'Núm. de Orden costo',
                'cmp_costcta':  'Cuenta/Plan de Ctas.',
                'cmp_imgcomp':  'Imagen del documento',
                'cmp_statreg':  'Estado del Reg.',
                }
        widgets = {
                'cmp_comprob':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cmp_ncuenta':  forms.Select(),
                # 'cmp_fechcmp':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                # 'cmp_usernam':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                # 'cmp_sucursa':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cmp_origpro':  forms.Select(),
                'cmp_origtra':  forms.Select(),
                'cmp_numorig':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cmp_tpoenti':  forms.Select(),
                'cmp_entidad':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cmp_mondalt':  forms.Select(),
                'cmp_mondaof':  forms.Select(),
                'cmp_cotizac':  forms.Select(),
                'cmp_cajanum':  forms.Select(),
                'cmp_cajeras':  forms.Select(),
                'cmp_detalle':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cmp_cantida':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cmp_tpomovi':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cmp_valores':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cmp_nivlcta':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cmp_periodo':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cmp_costord':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cmp_costcta':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                'cmp_imgcomp':  forms.ClearableFileInput(),
                'cmp_statreg':  forms.NumberInput(attrs={"class": "form_input", "autocomplete": "off"}),
                }


class SaldocontabForm(forms.ModelForm):

    class Meta:
        model = Saldocontab
        fields = [
                'slc_ncuenta',
                'slc_sucursa',
                'slc_saldinc',
                'slc_ingreso',
                'slc_egresos',
                'slc_saldact',
                'slc_inici01',
                'slc_inici02',
                'slc_inici03',
                'slc_inici04',
                'slc_inici05',
                'slc_inici06',
                'slc_inici07',
                'slc_inici08',
                'slc_inici09',
                'slc_inici10',
                'slc_inici11',
                'slc_inici12',
                'slc_ingre01',
                'slc_ingre02',
                'slc_ingre03',
                'slc_ingre04',
                'slc_ingre05',
                'slc_ingre06',
                'slc_ingre07',
                'slc_ingre08',
                'slc_ingre09',
                'slc_ingre10',
                'slc_ingre11',
                'slc_ingre12',
                'slc_egres01',
                'slc_egres02',
                'slc_egres03',
                'slc_egres04',
                'slc_egres05',
                'slc_egres06',
                'slc_egres07',
                'slc_egres08',
                'slc_egres09',
                'slc_egres10',
                'slc_egres11',
                'slc_egres12',
                'slc_actua01',
                'slc_actua02',
                'slc_actua03',
                'slc_actua04',
                'slc_actua05',
                'slc_actua06',
                'slc_actua07',
                'slc_actua08',
                'slc_actua09',
                'slc_actua10',
                'slc_actua11',
                'slc_actua12',
                ]
        labels = {
                'slc_ncuenta':  'Plancuenta',
                'slc_sucursa':  'Sucursal',
                'slc_saldinc':  'Saldo inicial',
                'slc_ingreso':  'Ingresos',
                'slc_egresos':  'Egresos',
                'slc_saldact':  'Saldo Actual',
                'slc_inici01':  'Saldo inici-01',
                'slc_inici02':  'Saldo inici-02',
                'slc_inici03':  'Saldo inici-03',
                'slc_inici04':  'Saldo inici-04',
                'slc_inici05':  'Saldo inici-05',
                'slc_inici06':  'Saldo inici-06',
                'slc_inici07':  'Saldo inici-07',
                'slc_inici08':  'Saldo inici-08',
                'slc_inici09':  'Saldo inici-09',
                'slc_inici10':  'Saldo inici-10',
                'slc_inici11':  'Saldo inici-11',
                'slc_inici12':  'Saldo inici-12',
                'slc_ingre01':  'Saldo ingre-01',
                'slc_ingre02':  'Saldo ingre-02',
                'slc_ingre03':  'Saldo ingre-03',
                'slc_ingre04':  'Saldo ingre-04',
                'slc_ingre05':  'Saldo ingre-05',
                'slc_ingre06':  'Saldo ingre-06',
                'slc_ingre07':  'Saldo ingre-07',
                'slc_ingre08':  'Saldo ingre-08',
                'slc_ingre09':  'Saldo ingre-09',
                'slc_ingre10':  'Saldo ingre-10',
                'slc_ingre11':  'Saldo ingre-11',
                'slc_ingre12':  'Saldo ingre-12',
                'slc_egres01':  'Saldo egres-01',
                'slc_egres02':  'Saldo egres-02',
                'slc_egres03':  'Saldo egres-03',
                'slc_egres04':  'Saldo egres-04',
                'slc_egres05':  'Saldo egres-05',
                'slc_egres06':  'Saldo egres-06',
                'slc_egres07':  'Saldo egres-07',
                'slc_egres08':  'Saldo egres-08',
                'slc_egres09':  'Saldo egres-09',
                'slc_egres10':  'Saldo egres-10',
                'slc_egres11':  'Saldo egres-11',
                'slc_egres12':  'Saldo egres-12',
                'slc_actua01':  'Saldo actua-01',
                'slc_actua02':  'Saldo actua-02',
                'slc_actua03':  'Saldo actua-03',
                'slc_actua04':  'Saldo actua-04',
                'slc_actua05':  'Saldo actua-05',
                'slc_actua06':  'Saldo actua-06',
                'slc_actua07':  'Saldo actua-07',
                'slc_actua08':  'Saldo actua-08',
                'slc_actua09':  'Saldo actua-09',
                'slc_actua10':  'Saldo actua-10',
                'slc_actua11':  'Saldo actua-11',
                'slc_actua12':  'Saldo actua-12',
                }
        widgets = {
                'slc_ncuenta':  forms.Select(),
                'slc_sucursa':  forms.Select(),
                'slc_saldinc':  forms.DecimalField(),
                'slc_ingreso':  forms.DecimalField(),
                'slc_egresos':  forms.DecimalField(),
                'slc_saldact':  forms.DecimalField(),
                'slc_inici01':  forms.DecimalField(),
                'slc_inici02':  forms.DecimalField(),
                'slc_inici03':  forms.DecimalField(),
                'slc_inici04':  forms.DecimalField(),
                'slc_inici05':  forms.DecimalField(),
                'slc_inici06':  forms.DecimalField(),
                'slc_inici07':  forms.DecimalField(),
                'slc_inici08':  forms.DecimalField(),
                'slc_inici09':  forms.DecimalField(),
                'slc_inici10':  forms.DecimalField(),
                'slc_inici11':  forms.DecimalField(),
                'slc_inici12':  forms.DecimalField(),
                'slc_ingre01':  forms.DecimalField(),
                'slc_ingre02':  forms.DecimalField(),
                'slc_ingre03':  forms.DecimalField(),
                'slc_ingre04':  forms.DecimalField(),
                'slc_ingre05':  forms.DecimalField(),
                'slc_ingre06':  forms.DecimalField(),
                'slc_ingre07':  forms.DecimalField(),
                'slc_ingre08':  forms.DecimalField(),
                'slc_ingre09':  forms.DecimalField(),
                'slc_ingre10':  forms.DecimalField(),
                'slc_ingre11':  forms.DecimalField(),
                'slc_ingre12':  forms.DecimalField(),
                'slc_egres01':  forms.DecimalField(),
                'slc_egres02':  forms.DecimalField(),
                'slc_egres03':  forms.DecimalField(),
                'slc_egres04':  forms.DecimalField(),
                'slc_egres05':  forms.DecimalField(),
                'slc_egres06':  forms.DecimalField(),
                'slc_egres07':  forms.DecimalField(),
                'slc_egres08':  forms.DecimalField(),
                'slc_egres09':  forms.DecimalField(),
                'slc_egres10':  forms.DecimalField(),
                'slc_egres11':  forms.DecimalField(),
                'slc_egres12':  forms.DecimalField(),
                'slc_actua01':  forms.DecimalField(),
                'slc_actua02':  forms.DecimalField(),
                'slc_actua03':  forms.DecimalField(),
                'slc_actua04':  forms.DecimalField(),
                'slc_actua05':  forms.DecimalField(),
                'slc_actua06':  forms.DecimalField(),
                'slc_actua07':  forms.DecimalField(),
                'slc_actua08':  forms.DecimalField(),
                'slc_actua09':  forms.DecimalField(),
                'slc_actua10':  forms.DecimalField(),
                'slc_actua11':  forms.DecimalField(),
                'slc_actua12':  forms.DecimalField(),
                }
