# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-07 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='soc_categor',
            field=models.CharField(blank=True, default='0', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='soc_celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='soc_correoe',
            field=models.EmailField(blank=True, max_length=75, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='soc_registr',
            field=models.CharField(blank=True, default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='soc_telefon',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono'),
        ),
    ]
