# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-13 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='soc_observa',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Observaciones'),
        ),
    ]
