# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-07 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_auto_20180806_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='soc_citynam',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='socio',
            name='soc_paisnam',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='socio',
            name='soc_statnam',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado / Porvincia'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='soc_fechreg',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de registración'),
        ),
    ]
