# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt_frsname', models.CharField(max_length=25, verbose_name='Primer Nombre')),
                ('cnt_lasname', models.CharField(max_length=25, verbose_name='Apellidos')),
                ('cnt_telefon', models.CharField(max_length=50, verbose_name='Núm. de teléfono')),
                ('cnt_correoe', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('cnt_fechmsj', models.DateTimeField(auto_now_add=True)),
                ('cnt_mensaje', models.CharField(max_length=250, verbose_name='Mensaje')),
            ],
        ),
    ]
