# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-07 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancuenta',
            name='id',
        ),
        migrations.AlterField(
            model_name='plancuenta',
            name='plc_ctabaln',
            field=models.CharField(max_length=1, verbose_name='Cuenta  de baalance'),
        ),
        migrations.AlterField(
            model_name='plancuenta',
            name='plc_ctanexo',
            field=models.CharField(max_length=1, verbose_name='Cta. para los anexos'),
        ),
        migrations.AlterField(
            model_name='plancuenta',
            name='plc_ncuenta',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='Núm. Planctas'),
        ),
        migrations.AlterField(
            model_name='plancuenta',
            name='plc_nivlcta',
            field=models.CharField(default='0', max_length=1, verbose_name='Nivel Cta. 1-7'),
        ),
    ]
