# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_frsname', models.CharField(max_length=15, verbose_name='Primer Nombre')),
                ('req_secname', models.CharField(max_length=25, verbose_name='Apellidos')),
                ('req_direcci', models.CharField(max_length=50, verbose_name='Dirección Domiciliaria')),
                ('req_zipcodg', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal')),
                ('req_correoe', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('req_fechmsj', models.DateField(verbose_name='Fecha de Mensaje')),
                ('req_descrip', models.TextField(default='Solicito exposición', max_length=25, verbose_name='Titulo')),
                ('req_mensaje', models.CharField(max_length=220, verbose_name='Mensaje')),
                ('req_requier', models.BooleanField(default=True)),
            ],
        ),
    ]
